### ISSUE TITLE
ModuleNotFoundError: No module named 'mdlp._mdlp'

### ISSUE THREAD

**Issue by NeilChangYanpeng** [hlin117/mdlp-discretization#37]
Hello,Henry,
I installed the package and ran the example code following the README.md

![image](https://user-images.githubusercontent.com/41663460/115327666-ec4a8980-a1c1-11eb-9407-839e93ad6411.png)

Then I got this error:

`D:\Anaconda3\envs\cdt\python.exe "E:/causal_discovery/minimum description length/mdlp-discretization-master/demo/demo.py"
Traceback (most recent call last):
  File "E:/causal_discovery/minimum description length/mdlp-discretization-master/demo/demo.py", line 1, in <module>
    from mdlp.discretization import MDLP
  File "E:\causal_discovery\minimum description length\mdlp-discretization-master\mdlp\discretization.py", line 17, in <module>
    from mdlp._mdlp import MDLPDiscretize
ModuleNotFoundError: No module named 'mdlp._mdlp'

Process finished with exit code 1`

Can you give me some help? Thank you.

**Comment by martino-vic** [comment]
Same, windows 10, python 3.9, jupyter lab

![Screenshot (826)](https://user-images.githubusercontent.com/53435298/132241956-64e7194c-7a03-4eba-8640-105c73c91d41.png)

I followed these instructions: https://stackoverflow.com/questions/7508803/how-do-i-import-function-from-pyx-file-in-python
Now I get this error:

ImportError: Building module mdlp._mdlp failed: ["distutils.errors.CompileError: command 'C:\\\\Program Files (x86)\\\\Microsoft Visual Studio\\\\2019\\\\BuildTools\\\\VC\\\\Tools\\\\MSVC\\\\14.28.29333\\\\bin\\\\HostX86\\\\x64\\\\cl.exe' failed with exit code 2\n"]

Some promising workaround: https://github.com/sammchardy/python-binance/issues/148

**Comment by 80070003** [comment]
Same question, did anybody solved it?

**Comment by elisammz** [comment]
Same problem. Did any get a solution? 
Python 3.8.18, MacOs
